### ISSUE TITLE
Failed->"properties" property should be found in root of JSON schema"

### ISSUE THREAD

**Issue by chris17453** [ethlo/jsons2xsd#11]
I'm not sure this is true. The examples I've seen from drafts 3 and up don't require properties to be present in the root node.

Possibly, I'm misunderstanding this. 

Could you clarify the versions this tool is applicable for?

**Comment by ethlo** [comment]
I'm not really sure either. I have not personally had the drive to develop this project further for the past 3 years, so at this point, I'm not as knowledgeable about the JSON "standard" as one should be. It was developed to fit my needs and got a major overhaul in the 2.x release. If you have ideas or PRs than I will be happy to assist, but I do not have the time to do major things on this project anymore.

**Comment by ethlo** [comment]
Closing issue. If you have an example schema that you believe should be supported, please provide a sample.
