### ISSUE TITLE
Type mapping does not include type=integer, format=int64

### ISSUE THREAD

**Issue by penguinInSpring** [ethlo/jsons2xsd#12]
Hey,
I'm just testing out your project. Thanks for the great lib!
Unfortunately, I'm running into some issues: The first json I want to convert throws an IllegalArgumentException. Looking into your code, the problem seems to be the type of this object which does not exist in your code. The json is the following:
{"User": {
		"type": "object",
		"properties": {
			"id": {
				"type": "integer",
				"format": "int64"
			},
			"key": {
				"type": "string"
			}
		}
	}
}
Am I missing something or is this combination not covered in your lib?

Thank you already for your reply!

**Comment by penguinInSpring** [comment]
Apparently there are some more type / format combinations that are not yet covered:
integer | int64 = long
integer | int32 = int
number | double = double
Could you add those types/formats to the project? I would really appreciate that.
Thank you. =)

**Comment by ethlo** [comment]
Hi! As far as I can tell those are not part of JSON schema specs, so I am a little hesitant to add them directly. However, I'm looking into the ability to add simple-type mappings to the configuration, then you can add any types you'd like.

**Comment by ethlo** [comment]
I just merged the ability to use custom mappings!

```java
        try (final Reader r = reader("/schema/customformats.json"))
        {
            final Config cfg = new Config.Builder()
                    .createRootElement(false)
                    .targetNamespace("http://ethlo.com/schema/custom-test-1.0.xsd")
                    .name("custom")
                    .ignoreUnknownFormats(true)
                    .customTypeMapping(JsonSimpleType.INTEGER, "int64", XsdSimpleType.LONG)
                    .customTypeMapping(JsonSimpleType.INTEGER, "int32", XsdSimpleType.INT)
                    .customTypeMapping(JsonSimpleType.STRING, "ext-ref", XsdSimpleType.STRING)
                    .build();
            final Document doc = Jsons2Xsd.convert(r, cfg);
            assertThat(XmlUtil.asXmlString(doc.getDocumentElement())).isXmlEqualTo(load("schema/customformats.xsd"));
        }
```
