### ISSUE TITLE
How to convert to XML Attributes in XSD ?

### ISSUE THREAD

**Issue by Pramodmk** [ethlo/jsons2xsd#15]
I am trying to convert a JSON Schema to XSD. I need few entities to come as attributes but they are coming as elements? How can i achieve that? Is there something to specify as part of JSON Schema or something at Config level?

`Actual : <element name="ABCD" type="string"/>`
`Expected: <attribute name="ABCD" type="xs:string"/>`

**Comment by ethlo** [comment]
Unfortunately this is not supported. This would require something like a custom attribute in the JSON schema or a mapping structure allowing you to express what should be attributes/elements, which would then be easier to just clean up manually after the first conversion.
