### ISSUE TITLE
Genearted invalid xsd

### ISSUE THREAD

**Issue by katwe123** [ethlo/jsons2xsd#16]
Hi Team,
First of all I would like to thank your team.

I am not sure whether its bug or not, i just wanted notify my issue.. as i hv attached my "input_json" and "expected_json", the output i am not getting as expected, please help to do the needful.

[input_json.txt](https://github.com/ethlo/jsons2xsd/files/2966592/input_json.txt)
[expected_json.txt](https://github.com/ethlo/jsons2xsd/files/2966598/expected_json.txt)

and also my requirement is if type not found the default to object - to do this i hv made changes to code at line no 526 in Jsons2Xsd class

else if(jsonType == null && jsonFormat==null ) {
        	return XsdComplexType.OBJECT_VALUE;
 }

[invalid_output.txt](https://github.com/ethlo/jsons2xsd/files/2966674/invalid_output.txt)
this is the output presently i am getting which is invalid and i validated -http://www.utilities-online.info/xsdvalidation

Note - line no's to look in attached files:
1) input_json - 40
2) expected_json - start from 25
3) invalid_output - 35

Thank you.

**Comment by lbovet** [comment]
This is fixed by #19. Will be available in version 2.2.0.
Issue can be closed.
