### ISSUE TITLE
Return null when using your example

### ISSUE THREAD

**Issue by i326998** [ethlo/jsons2xsd#17]
I'm using the following code to convert json schema to xsd:
InputStream inputStream = new ClassPathResource("The-path-to-the-file").getInputStream();
try (final BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream)))
        {
            final Config cfg = new Config.Builder().targetNamespace("http://example.com/myschema.xsd").name("array").build();
            final Document doc = Jsons2Xsd.convert(reader, cfg);
        }
The inputStream has the content that you write in your example:
{
  "type":"array",
  "items":{
    "type":"object",
    "properties":{
      "price":{
        "type":"number",
        "minimum":0
      },
      "name":{
        "type":"string",
        "minLength":5,
        "maxLength":32
      },
      "isExpired":{
        "default":false,
        "type":"boolean"
      },
      "manufactured":{
        "type":"string",
        "format":"date-time"
      }
    },
    "required":[
      "price",
      "name",
      "manufactured"
    ]
  }
}

However, the returned variable "doc" is null !

**Comment by ethlo** [comment]
Hi! I'm sorry you cannot get it to work. Please have a look at ConversionTest.java, and especially the test `testArraySchema`.
