### ISSUE TITLE
Simple types in definitions are ignored

### ISSUE THREAD

**Issue by lbovet** [ethlo/jsons2xsd#18]
Only objects are supported in definitions. It should also be possible to have simple types there.

**Comment by ethlo** [comment]
Thanks a lot for your contribution!

**Comment by lbovet** [comment]
With pleasure! Can you roll a new release, so that we can get rid of our own custom version? Thanks!

**Comment by ethlo** [comment]
I will, as soon as Sonatype get their stuff up and running! https://status.maven.org/ :)

**Comment by lbovet** [comment]
Oh. Wait. I just encountered a schema that is failing. Looks like there is a small bug somewhere.
I am going to fix that and make a new PR.
