### ISSUE TITLE
Configuration to control array element names

### ISSUE THREAD

**Issue by lbovet** [ethlo/jsons2xsd#22]
Currently, array elements are named after the JSON schema name.
In order to control or avoid using type names in the XML instances, it should be possible to choose how these elements are named.

**Proposal**
`Config.mapArrayElementNames(Function<String,String> mapper)`
default is the identity function

**Examples**
If one wants names in camelCase:
`cfg.mapArrayElementNames(name -> name.substring(0, 1).toLowerCase() + name.substring(1))`

If one wants to use "item" everywhere:
`cfg.mapArrayElementNames(name -> "item")`

You can assign to me. It will be shortly done and can be included in 2.2.0.

**Comment by ethlo** [comment]
I take this will be the last ticket for 2.2.0 then. Let me know when the PR is ready :)

**Comment by lbovet** [comment]
Thanks for the quick release!
BTW, I have a written a rudimentary maven plugin: https://github.com/swisspush/jsons2xsd-maven-plugin
