### ISSUE TITLE
2.3.0 release didn't update the pom or readme for the new version

### ISSUE THREAD

**Issue by bbezanson** [ethlo/jsons2xsd#35]
The pom.xml has the version at the previous 2.2.1 and the readme.md uses the example for 2.2.0 (in case someone is quickly copy/pasting the maven section.

The question is whether the current master was built and replaced the original 2.2.1 release. I know artifactory only allows publishing a single release version and if you have a mistake you need to bump the version and republish.

**Comment by ethlo** [comment]
The version published to Maven central is the correct one.
