### ISSUE TITLE
Creating XSD from non-object type

### ISSUE THREAD

**Issue by bj0rj0h** [ethlo/jsons2xsd#8]
Hi 

First of all I want to say thanks for a great tool.

I'm getting java.lang.IllegalArgumentException: root should have type="object" when using a schema that is not starting with object such as. 

```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "price": {
                "type": "number"
            },
            "name": {
                "type": "string"
            },
            "isExpired": {
                "default": false,
                "type": "boolean"
            }
        }
    }
}
```

Am I doing something wrong here or is this a bug?

Thanks
Björn

**Comment by ethlo** [comment]
Hi! Thanks for taking the time to try this tool! 
I have just created a _2.0-SNAPSHOT_ release, please see the updated front page (https://github.com/ethlo/jsons2xsd) for how to test it. Please note the new API and Maven coordinates.
