### ISSUE TITLE
47 compile errors only

### ISSUE THREAD

**Issue by PerDFSjov** [ethlo/jsons2xsd#9]
Using java JDK-9.04 on Windows 10
 
C:\repos\SRSFormatService\jsons2xsd-master\jsons2xsd-master\src\main\java\com\ethlo\jsons2xsd>"C:\Program Files\Java\jdk-9.0.4\bin\javac" *.java
Jsons2Xsd.java:45: error: package com.fasterxml.jackson.databind does not exist
import com.fasterxml.jackson.databind.JsonNode;
                                     ^
Jsons2Xsd.java:46: error: package com.fasterxml.jackson.databind does not exist
import com.fasterxml.jackson.databind.ObjectMapper;
                                     ^
Jsons2Xsd.java:47: error: package com.fasterxml.jackson.databind.node does not exist
import com.fasterxml.jackson.databind.node.ArrayNode;
                                          ^
Jsons2Xsd.java:121: error: cannot find symbol
    private static final ObjectMapper mapper = new ObjectMapper();
                         ^
  symbol:   class ObjectMapper
  location: class Jsons2Xsd
Jsons2Xsd.java:171: error: cannot find symbol
    private static void handleArraySchema(Config cfg, JsonNode rootNode, Element schemaRoot, Set<String> neededElements)
                                                      ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:204: error: cannot find symbol
    private static void handleObjectSchema(Config cfg, final JsonNode rootNode, final Element schemaRoot, final Set<String> neededElements)
                                                             ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:231: error: cannot find symbol
    private static void doIterateDefinitions(Set<String> neededElements, Element elem, JsonNode node, Config cfg)
                                                                                       ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:277: error: cannot find symbol
    private static void handleObject(Set<String> neededElements, String key, Element elem, JsonNode node, Config cfg)
                                                                                           ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:295: error: cannot find symbol
    private static void handleChoice(Set<String> neededElements, Element elem, ArrayNode oneOf, Config cfg)
                                                                               ^
  symbol:   class ArrayNode
  location: class Jsons2Xsd
Jsons2Xsd.java:312: error: cannot find symbol
    private static void doIterate(Set<String> neededElements, Element elem, JsonNode node, List<String> requiredList, Config cfg)
                                                                            ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:337: error: cannot find symbol
    private static void doIterateSingle(Set<String> neededElements, String name, JsonNode val, Element elem, boolean required, Config cfg)
                                                                                 ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:387: error: cannot find symbol
    private static void handleReference(Set<String> neededElements, Element nodeElem, JsonNode val, Config cfg)
                                                                                      ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:404: error: cannot find symbol
    private static void handleString(Element nodeElem, JsonNode val)
                                                       ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:437: error: cannot find symbol
    private static void handleEnum(Element nodeElem, JsonNode val)
                                                     ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:452: error: cannot find symbol
    private static void handleNumber(Element nodeElem, String xsdType, JsonNode jsonNode)
                                                                       ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:478: error: cannot find symbol
    private static void handleArray(Set<String> neededElements, Element nodeElem, JsonNode jsonNode, Config cfg)
                                                                                  ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:488: error: cannot find symbol
    private static void handleArrayElements(Set<String> neededElements, JsonNode jsonNode, final JsonNode arrItems, final String arrayXsdType, final Element arrElem, Config cfg)
                                                                        ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:488: error: cannot find symbol
    private static void handleArrayElements(Set<String> neededElements, JsonNode jsonNode, final JsonNode arrItems, final String arrayXsdType, final Element arrElem, Config cfg)
                                                                                                 ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:513: error: cannot find symbol
    private static String determineXsdType(String key, JsonNode node)
                                                       ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:537: error: cannot find symbol
    private static Integer getIntVal(JsonNode node, String attribute)
                                     ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:553: error: cannot find symbol
    private static List<String> getRequiredList(JsonNode jsonNode)
                                                ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
XmlUtil.java:56: error: package com.sun.xml.xsom.parser does not exist
import com.sun.xml.xsom.parser.XSOMParser;
                              ^
Jsons2Xsd.java:121: error: cannot find symbol
    private static final ObjectMapper mapper = new ObjectMapper();
                                                   ^
  symbol:   class ObjectMapper
  location: class Jsons2Xsd
Jsons2Xsd.java:130: error: cannot find symbol
        final JsonNode rootNode = mapper.readTree(jsonSchema);
              ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:150: error: cannot find symbol
        JsonNode definitions;
        ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:153: error: cannot find symbol
            final JsonNode definitionsRootNode = mapper.readTree(definitionSchema);
                  ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:173: error: cannot find symbol
        final JsonNode items = rootNode.path(FIELD_ITEMS);
              ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:206: error: cannot find symbol
        JsonNode properties;
        ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:233: error: cannot find symbol
        final Iterator<Entry<String, JsonNode>> iter = node.fields();
                                     ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:236: error: cannot find symbol
            final Entry<String, JsonNode> entry = iter.next();
                                ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:238: error: cannot find symbol
            final JsonNode val = entry.getValue();
                  ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:279: error: cannot find symbol
        final JsonNode properties = node.get(FIELD_PROPERTIES);
              ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:290: error: cannot find symbol
            final ArrayNode oneOf = (ArrayNode) node.get("oneOf");
                  ^
  symbol:   class ArrayNode
  location: class Jsons2Xsd
Jsons2Xsd.java:290: error: cannot find symbol
            final ArrayNode oneOf = (ArrayNode) node.get("oneOf");
                                     ^
  symbol:   class ArrayNode
  location: class Jsons2Xsd
Jsons2Xsd.java:299: error: cannot find symbol
        for (JsonNode e : oneOf)
             ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:302: error: cannot find symbol
            final JsonNode refs = e.get(JSON_REF);
                  ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:316: error: cannot find symbol
            final Iterator<Entry<String, JsonNode>> fieldIter = node.fields();
                                         ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:319: error: cannot find symbol
                final Entry<String, JsonNode> entry = fieldIter.next();
                                    ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:321: error: cannot find symbol
                final JsonNode val = entry.getValue();
                      ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:328: error: cannot find symbol
            for (JsonNode entry : node)
                 ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:331: error: cannot find symbol
                final JsonNode val = entry;
                      ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:389: error: cannot find symbol
        final JsonNode refs = val.get(JSON_REF);
              ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:443: error: cannot find symbol
        final JsonNode enumNode = val.get("enum");
              ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:480: error: cannot find symbol
        final JsonNode arrItems = jsonNode.path("items");
              ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
Jsons2Xsd.java:561: error: cannot find symbol
        for (JsonNode requiredField : jsonNode.withArray(FIELD_REQUIRED))
             ^
  symbol:   class JsonNode
  location: class Jsons2Xsd
XmlUtil.java:117: error: cannot find symbol
        XSOMParser parser = new XSOMParser(factory);
        ^
  symbol:   class XSOMParser
  location: class XmlUtil
XmlUtil.java:117: error: cannot find symbol
        XSOMParser parser = new XSOMParser(factory);
                                ^
  symbol:   class XSOMParser
  location: class XmlUtil
47 errors

C:\repos\SRSFormatService\jsons2xsd-master\jsons2xsd-master\src\main\java\com\ethlo\jsons2xsd>

**Comment by ethlo** [comment]
Hi! You need to compile it using Maven, or manually need to provide all dependencies and add them to your build classpath.

**Comment by PerDFSjov** [comment]
Hello,

Thanks, I realized just that after my post, sorry.
I'm a .NET developer only and the closest I've gotten to Java is during my morning coffee

Thanks for your reply and please feel free to delete my stupid post!

BR,
Per

Sent from my iPhone

13 feb. 2018 kl. 20:41 skrev Morten Haraldsen <notifications@github.com<mailto:notifications@github.com>>:


Hi! You need to compile it using Maven, or manually need to provide all dependencies and add them to your build classpath.
